name = "rapphimchill"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
# Thêm biến môi trường nếu có

[site]
bucket = ".vercel/output/static"

[[kv_namespaces]]
# Nếu bạn dùng KV

[[r2_buckets]]
# Nếu bạn dùng R2
